# -*- coding: utf-8 -*-

FEEDS = ({'label': 'The Apple Byte',
         'HD': 'http://feeds2.feedburner.com/cnet/applebytehd',
         'SD' : 'http://feeds2.feedburner.com/cnet/applebyte',
         'thumb' : 'applebyte.jpg'},
         {'label' : 'Car Tech',
         'HD' : 'http://feeds2.feedburner.com/cnet/cartechvideohd',
         'SD' : 'http://feeds2.feedburner.com/cnet/cartechvideo',
         'thumb' : 'car_tech.jpg'},
         {'label' : 'CNET Conversations',
         'HD' : 'http://feeds.feedburner.com/cnet/conversationshd',
         'SD' : 'http://feeds.feedburner.com/cnet/conversations',
         'thumb' : 'conversations.jpg'},
         {'label' : 'CNET News',
         'HD' : 'http://feeds.feedburner.com/cnet/cnetnewshd',
         'SD' : 'http://feeds.feedburner.com/cnet/news',
         'thumb' : 'cnet_news.jpg'},
         {'label' : 'CNETs Top 5',
         'HD' : 'http://feeds2.feedburner.com/cnet/top5hd',
         'SD' : 'http://feeds2.feedburner.com/cnet/top5',
         'thumb' : 'cnet_top_5.jpg'},
         {'label' : 'Device & Conquer',
         'HD' : 'http://feeds.feedburner.com/DeviceConquerhd',
         'SD' : 'http://feeds.feedburner.com/deviceconquersd',
         'thumb' : 'device_conquer.jpg'},
         {'label' : 'First Look',
         'HD' : 'http://feeds.feedburner.com/cnet/firstlookhd',
         'SD' : 'http://feeds.feedburner.com/cnet/firstlook',
         'thumb' : 'firstlook.jpg'},
         {'label' : 'How To',
         'HD' : 'http://feeds2.feedburner.com/cnet/howtohd',
         'SD' : 'http://feeds2.feedburner.com/cnet/howto',
         'thumb' : 'howto.jpg'},
         {'label' : 'Prizefight',
         'HD' : 'http://feeds2.feedburner.com/cnet/prizefighthd',
         'SD' : 'http://feeds2.feedburner.com/cnet/prizefight',
         'thumb' : 'prizefight.jpg'},
         {'label' : 'Tap That App',
         'HD' : 'http://feeds.feedburner.com/cnet/tapthatapphd',
         'SD' : 'http://feeds.feedburner.com/cnet/tapthatapp',
         'thumb' : 'tapThatApp.jpg'},
         {'label' : '*All CNET Video Podcasts*',
         'HD' : 'http://feeds2.feedburner.com/cnet/allhdpodcast',
         'SD' : 'http://feeds2.feedburner.com/allcnetvideopodcasts',
         'thumb' : 'all_video.jpg'})
